#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIST_DIR="$ROOT_DIR/dist"
RELEASE_DIR="$DIST_DIR/release"
PKG_NAME="${PKG_NAME:-manga-tracker-linux}"
PKG_DIR="$RELEASE_DIR/$PKG_NAME"
ARCHIVE_PATH="$RELEASE_DIR/${PKG_NAME}.tar.gz"
SOURCE_BINARY="${BINARY_PATH:-$DIST_DIR/manga-tracker}"
RELEASE_BINARY_PATH="$RELEASE_DIR/manga-tracker"
CREATE_DRAFT_RELEASE="${CREATE_DRAFT_RELEASE:-1}"
RELEASE_PRERELEASE="${RELEASE_PRERELEASE:-1}"
GH_REPO="${GH_REPO:-}"
RELEASE_NOTES="${RELEASE_NOTES:-Automated draft release generated by scripts/build-release-package.sh}"

require_tool() {
  local cmd="$1"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "Missing required tool: $cmd"
    exit 1
  fi
}

require_tool tar
require_tool sha256sum

if [[ "${SKIP_BINARY_BUILD:-0}" != "1" ]]; then
  echo "[1/5] Building binary"
  "$ROOT_DIR/scripts/build-binary.sh"
fi

if [[ ! -x "$SOURCE_BINARY" ]]; then
  echo "Binary not found or not executable: $SOURCE_BINARY"
  exit 1
fi

echo "[2/5] Preparing release package folder"
rm -rf "$PKG_DIR"
mkdir -p "$PKG_DIR"

install -m 755 "$SOURCE_BINARY" "$PKG_DIR/manga-tracker"
install -m 755 "$ROOT_DIR/release/linux/install_systemd_service.sh" "$PKG_DIR/install_systemd_service.sh"
install -m 755 "$ROOT_DIR/release/linux/uninstall_systemd_service.sh" "$PKG_DIR/uninstall_systemd_service.sh"
install -m 644 "$ROOT_DIR/release/linux/LINUX_INSTALL.md" "$PKG_DIR/LINUX_INSTALL.md"
install -m 644 "$ROOT_DIR/.env.example" "$PKG_DIR/.env.example"
install -m 644 "$ROOT_DIR/src/web/dashboard.html" "$PKG_DIR/dashboard.html"
install -m 644 "$ROOT_DIR/src/web/dashboard.css" "$PKG_DIR/dashboard.css"

echo "[3/5] Creating archive $ARCHIVE_PATH"
mkdir -p "$RELEASE_DIR"
tar -C "$RELEASE_DIR" -czf "$ARCHIVE_PATH" "$PKG_NAME"

echo "[4/5] Writing release assets"
install -m 755 "$SOURCE_BINARY" "$RELEASE_BINARY_PATH"
sha256sum "$ARCHIVE_PATH" > "${ARCHIVE_PATH}.sha256"

echo "Release package ready:"
echo "  $RELEASE_BINARY_PATH"
echo "  $ARCHIVE_PATH"
echo "  ${ARCHIVE_PATH}.sha256"

if [[ "$CREATE_DRAFT_RELEASE" != "1" ]]; then
  exit 0
fi

require_tool gh
require_tool node

RELEASE_TAG="${RELEASE_TAG:-v$(cd "$ROOT_DIR" && node -e "console.log(require('./src/config').BOT_VERSION)")}"
RELEASE_TITLE="${RELEASE_TITLE:-$RELEASE_TAG}"
ASSETS=("$RELEASE_BINARY_PATH" "$ARCHIVE_PATH" "${ARCHIVE_PATH}.sha256")
GH_REPO_ARGS=()
if [[ -n "$GH_REPO" ]]; then
  GH_REPO_ARGS=(--repo "$GH_REPO")
fi

if gh release view "$RELEASE_TAG" "${GH_REPO_ARGS[@]}" >/dev/null 2>&1; then
  echo "[5/5] Uploading assets to existing release $RELEASE_TAG"
  gh release upload "$RELEASE_TAG" "${ASSETS[@]}" --clobber "${GH_REPO_ARGS[@]}"
else
  echo "[5/5] Creating draft release $RELEASE_TAG"
  RELEASE_FLAGS=(--draft)
  if [[ "$RELEASE_PRERELEASE" == "1" ]]; then
    RELEASE_FLAGS+=(--prerelease)
  fi
  gh release create "$RELEASE_TAG" "${ASSETS[@]}" \
    "${RELEASE_FLAGS[@]}" \
    --title "$RELEASE_TITLE" \
    --notes "$RELEASE_NOTES" \
    "${GH_REPO_ARGS[@]}"
fi
