#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Stable release wrapper around the shared package/release flow.
RELEASE_PRERELEASE="${RELEASE_PRERELEASE:-0}"
RELEASE_NOTES="${RELEASE_NOTES:-Automated release generated by scripts/build-release-package.sh}"

export RELEASE_PRERELEASE
export RELEASE_NOTES

exec "$ROOT_DIR/scripts/build-prerelease-package.sh"
